Feature/player surrender
Game-as-a-Service/HUNTER-Gungi pull request #10
Opened 2023-04-25 16:33 UTC by zhihdd

# Description

# How to test

# New Dependencies

2023-05-15 22:36 UTC, allenh requested changes
* Please update `README.md` with the vocabulary translation
* Do we want unit tests and are we enforcing a minimum unit test coverage?
* What's the idea hind having files that are getting implemented by their respective implementation classes living under `/usecases` and not with their implementation class folder?  Eg: why is `repositoy.abstract.ts` under `/usecase` and not under `/repository`?

If the idea is that `usecase` is supposed to include all the business logic then would it make sense to rename `usecase` to `service` and group all the use case methods under their logical business logical name? For example `surrender` and `furigoma` use-cases could both be under `GungiService`:
```ts
class GungiService {
  async furigoma() {}
  async surrender() {}
}
```

2023-05-16 13:55 UTC, zhihdd commented on server/package.json
> +    "test:all": "npm run test:unit && npm run test:e2e"
Fix by closing database connection after alll test

2023-05-16 14:05 UTC, zhihdd commented on server/src/usecases/repository.abstract.ts
> +export default abstract class IRepository<T> {
I thougt interface can not be used by IoC container. But, after couple trying, it is work.

2023-05-23 01:42 UTC, allenh reviewed
I think overall this PR is in a good spot to merge. There are still some minor issues that need fixing but in the interest of time and progress I don't think these issues warrant a merge block and these issues can be fixed later on. If everyone is ok with how the project looks and after #14 is merged to unblock the pipeline then we can merge this to master.

2023-05-23 17:29 UTC, noracami approved these changes
LGTM

2023-05-24 03:22 UTC, merged