Set configuration of level beginner
Game-as-a-Service/HUNTER-Gungi pull request #19
Opened 2023-05-25 16:03 UTC by allyusd

# Description
- set configuration of level beginner.
- please develop feature by ATDD and TDD.

# How to test
```
// api route
{POST} /gungi/:gungiId/configuration

// request
none

// response 
status: 200
{
 gomas: {
      name: string, // 棋子的名稱
      side: string, // 黑 or 白
      coordinate: { x: int, y: int, z: int }
   }[]
}
```

# New Dependencies

2023-06-12 05:14 UTC, allenh requested changes
* The end to end test file is becoming a giant spaghetti file. It's more appropriate to divide the file based on domain since we only run E2E against domains. It's not your fault but someone has to do the grunt work since it wasn't done at the beginning.
* Please include a new E2E test case where the game has already started and the user wants to call `POST gungi/:id/configuration` again.

2023-06-12 05:14 UTC, allenh commented on server/src/usecases/service-class/SurrenderUsecase.ts
> +  async execute<R>(request: SurrenderRequest, presenter: Presenter<R>) {
What's the purpose of having an anonymous type here? The presenter type can be more strict by saying it's `SurrenderPresenter` instead of any other presenter type as no other presenter makes sense to be here.

2023-06-12 05:14 UTC, allenh commented on server/src/usecases/service-class/ConfigurationUsecase.ts
> +  async execute<R>(request: ConfigurationRequest, presenter: Presenter<R>) {
Same as the `SurrenderUsecase.execute`.

2023-06-12 05:14 UTC, allenh commented on server/test/unitTest/gungi.configuration.spec.ts
> +function expectGomaCountInOki(
same as the above comment but on line 318.

2023-06-12 05:14 UTC, allenh commented on server/test/unitTest/gungi.configuration.spec.ts
> +function expectGomaInHan(
this is referenced once therefore it should just be a function declared within the unit test on line 314.

2023-06-12 05:14 UTC, allenh commented on server/test/unitTest/gungi.configuration.spec.ts
> +    describe('入門級別 棋子要在指定位置', () => {
Interesting. This is a pretty creative way of writing tests.

2023-06-12 12:53 UTC, allyusd commented on server/src/domain/GungiHan.ts
> +    // console.log(JSON.stringify(this._han));
已修改

2023-06-12 13:04 UTC, allyusd commented on server/src/domain/GungiHan.ts
> +export const HAN_X_MAX = 9;
These should go in a "constants" file.
是指像目前 constant 底下的嗎？

是單純建一個 GungiHandDef.ts 檔案 (命名？)
然後直接搬過去？
```ts
export const EMPTY_GOMA = null;
export const HAN_X_MAX = 9;
export const HAN_Y_MAX = 9;
export const HAN_Z_MAX = 3;
```
還是需要弄一個 enum
```ts
enum GungiHandDef {
  EmptyGoma = null,
  HanMaxX = 9,
  HanMaxY = 9,
  HanMaxZ = 3,
}
```

2023-06-12 13:06 UTC, allyusd commented on server/src/frameworks/data-services/data-model/GungiDataModel.ts
> +    for (let x = 1; x <= HAN_X_MAX; x++) {
不確定是不是指這樣？

```ts
    for (let x = 0; x < HAN_X_MAX; x++) {
      for (let y = 0; y < HAN_Y_MAX; y++) {
        for (let z = 0; z < HAN_Z_MAX; z++) {
          const coordinate = new Coordinate(x + 1, y + 1, z + 1);
          const goma = gungiHan.findGoma(coordinate);
          if (goma !== EMPTY_GOMA) {
            gomasData.push(this.gomaToData(goma, coordinate));
          }
        }
      }
    }
```

2023-06-12 13:06 UTC, allyusd commented on server/src/usecases/service-class/SurrenderUsecase.ts
> +  async execute<R>(request: SurrenderRequest, presenter: Presenter<R>) {
同樣是同步 #18 的部份，需要再確認一下

2023-06-12 13:12 UTC, allyusd commented on server/test/unitTest/gungi.configuration.spec.ts
> +function expectGomaCountInOki(
已修改

2023-06-12 13:13 UTC, allyusd commented on server/test/unitTest/gungi.configuration.spec.ts
> +function expectGomaInHan(
已修改

2023-06-12 13:14 UTC, allyusd commented on server/test/unitTest/gungi.configuration.spec.ts
> +    describe('入門級別 棋子要在指定位置', () => {
因為在寫的過程一直重覆貼上，所以覺得可以用 DataSet 的方式來處理

2023-06-12 17:02 UTC, allenh commented on server/src/domain/goma/Goma.ts
>    abstract arata(to: Coordinate): void;
Sure, that ticket would be more appropriate for this discussion.

2023-06-12 17:04 UTC, allenh commented on server/src/domain/GungiHan.ts
> +export const HAN_X_MAX = 9;
We would just have a `constants.ts` that holds these constants such as:
```ts
// constants.ts
export const EMPTY_GOMA = null;
export const HAN_X_MAX = 9;
export const HAN_Y_MAX = 9;
export const HAN_Z_MAX = 3;
```

2023-06-12 17:08 UTC, allenh commented on server/src/frameworks/data-services/data-model/GungiDataModel.ts
> +    for (let x = 1; x <= HAN_X_MAX; x++) {
Yes but the coordinate also doesn't need an offset. Essentially you would start counting at `0` and ignore all offsets unless you are sending this to the clients/users. This means this line `const coordinate = new Coordinate(x + 1, y + 1, z + 1);` would become `const coordinate = new Coordinate(x, y, z);` where `x` and `y` will be in `[0,9)`, and z will be in `[0, 2)`.

Also even when sending this to clients we don't necessary need to add offset as long as everything is kept consistent. The idea is to avoid having logical bugs with offsets when it doesn't give any real benefit in code.

2023-06-12 17:18 UTC, allenh commented on server/src/usecases/service-class/ConfigurationUsecase.ts
> +  async execute<R>(request: ConfigurationRequest, presenter: Presenter<R>) {
Same comment: https://github.com/Game-as-a-Service/HUNTER-Gungi/pull/19#discussion_r1226993946

2023-06-13 03:49 UTC, allyusd commented on server/src/domain/GungiHan.ts
> +export const HAN_X_MAX = 9;
已修改

2023-06-13 03:58 UTC, allyusd commented
> * The end to end test file is becoming a giant spaghetti file. It's more appropriate to divide the file into smaller e2e files based on domains since we run E2E against domains and their individual route. It's not your fault but someone has to do the grunt work because it wasn't done at the beginning.
> * Please include a new E2E test case where the game has already started and the user wants to call `POST gungi/:id/configuration` again. The endpoint should return an error when this happens.

(不知道能不能這樣回？)
已拆出獨立 file
新的測項尚未建立

2023-06-13 03:59 UTC, allyusd commented on server/src/domain/goma/Goma.ts
>    abstract arata(to: Coordinate): void;
那這邊要 resolve 還是？

2023-06-13 04:01 UTC, allyusd commented on server/src/frameworks/data-services/data-model/GungiDataModel.ts
> +    for (let x = 1; x <= HAN_X_MAX; x++) {
可以理解，不過跟之前小智討論時的定義有衝突，
之前的定義是：「除了gungiHan內是用0-base處理，對外都是1-base」，
你們可以再討論一下

2023-06-13 04:04 UTC, allyusd commented on server/src/gateway/controllers/Gungi.controller.ts
> +  @Post('/gungi/:id/configuration')
同意使用動詞 configure，要請小智確認一下是否同意變更，因為這是在 issue 上直接定義的。

這個想法，似乎是把 beginning 等級的棋盤配置獨立出另一個 endpoint 的感覺。
我會覺得似乎保持在同一個會比較好？

2023-06-13 04:07 UTC, allyusd commented on server/src/usecases/Presenter.ts
> +export default interface Presenter<R> {
同步 #18，一樣請小智幫忙回答，如果跟另一個 comment 是同樣的原因可以回併討論

2023-06-13 04:16 UTC, allyusd commented on server/src/gateway/presenter/ConfigurationPresenter.ts
> +    const event = events[0] as ConfigurationEvent;
同樣同步 #18，要請小智幫忙回答。

目前對於 Event 沒有完整概念，從目前的設計上來看，保留了一個 command 可以傳出多個 event 的可能性。
同意，這邊沒有任何檢查，如果改成這樣有滿足嗎？

```ts
    const event = events.filter(
      (e) => e.name === 'Configuration',
    )[0] as ConfigurationEvent;
 ```

2023-06-13 04:29 UTC, allyusd commented on server/src/usecases/service-class/SurrenderUsecase.ts
> +  async execute<R>(request: SurrenderRequest, presenter: Presenter<R>) {
這邊應該是使用的地方，實際上小智要處理的是在 ConfigurationPresenter.ts

```ts ConfigurationPresenter.ts
export default class ConfigurationPresenter
  implements Presenter<ConfigurationView>
{
```

另外，這是 use case，如果像上面範例直接宣告 SurrenderPresenter, SurrenderView
這兩者來至 gateway， use case 使用 gateway 違反 CA 跨層原則。

2023-06-17 12:43 UTC, allyusd commented on server/src/frameworks/data-services/data-model/GungiDataModel.ts
> +    for (let x = 1; x <= HAN_X_MAX; x++) {
自補：小組討論後，決定除了 UI 畫面顯示，所有程式統一使用 0-base

2023-06-17 12:44 UTC, allyusd commented on server/src/usecases/service-class/SurrenderUsecase.ts
> +  async execute<R>(request: SurrenderRequest, presenter: Presenter<R>) {
補充：小組討論後，維持現況

2023-06-17 12:47 UTC, allyusd commented on server/src/gateway/controllers/Gungi.controller.ts
> +  @Post('/gungi/:id/configuration')
這裡不太懂 restful api 跟這幾個選擇的關係

/gungi/:id/configuration
/gungi/:id/configure
/gungi/:id/initialize

2023-06-17 12:47 UTC, allyusd commented on server/src/usecases/Presenter.ts
> +export default interface Presenter<R> {
補充：小組討論後，維持現況

2023-06-17 13:33 UTC, allyusd commented on server/src/frameworks/data-services/data-model/GungiDataModel.ts
> +    for (let x = 1; x <= HAN_X_MAX; x++) {
已修改

2023-06-17 13:37 UTC, allyusd commented on server/src/domain/Gungi.ts
> +    const addGomaToHan = (
extract constant 已修改
function move out / move in 待討論

2023-06-17 13:39 UTC, allyusd commented on server/src/domain/events/ConfigurationEvent.ts
> +    blackOki: GomaOki;
已修改

2023-06-17 13:44 UTC, allyusd commented on server/src/gateway/presenter/ConfigurationPresenter.ts
> +    const event = events[0] as ConfigurationEvent;
event 保持 [] 不變
使用 event 前加上 filter 判斷

2023-06-17 13:47 UTC, allyusd commented on server/src/gateway/presenter/ConfigurationPresenter.ts
> +      blackOki: [],
已修改

2023-06-17 13:59 UTC, allyusd commented on server/src/gateway/presenter/ConfigurationPresenter.ts
> +    }
extract method 完成

既然後都是跑遍棋盤內的每一個位置，何不用forEach/ map解決?
這句我不太懂意思？

2023-06-17 14:22 UTC, allyusd commented on server/src/gateway/presenter/ConfigurationPresenter.ts
> +    }
forEach 已修改

2023-06-17 14:52 UTC, allyusd commented on server/test/e2e/configuration.e2e-spec.ts
> +    };
已修改 extract method given_CreateGameAndFurigomaDone

2023-06-17 14:54 UTC, allyusd commented on server/test/e2e/configuration.e2e-spec.ts
> +    };
已修改 given_createGame_furigoma

2023-06-17 14:55 UTC, allyusd commented on server/test/e2e/configuration.e2e-spec.ts
> +      .send(body);
已修改

2023-06-17 14:56 UTC, allyusd commented on server/test/e2e/configuration.e2e-spec.ts
> +    }
待討倫，確認 coding style

2023-06-17 15:11 UTC, allyusd commented on server/test/e2e/configuration.e2e-spec.ts
> +    };
rename given_gungi_and_furigoma_done

2023-07-04 12:40 UTC, zhihdd approved these changes
LGTM

2023-07-04 13:16 UTC, allenh approved these changes

2023-07-04 13:21 UTC, merged