Feature/18 arata
Game-as-a-Service/HUNTER-Gungi pull request #21
Opened 2023-06-23 06:24 UTC by zhihdd

# Description
execute arata to put goma to specific coordinate at gugnihan from gomaoki

# How to test
run all  unit test and e2e test
```
npm run test
```
// api route
`{POST} /gungi/:gungiId/arata
`
// request
```
{
 playerId: string,
   goma: {
    name :string,
    side: string
  }, 
  to: {
     x: int, y: int, z: int 
  }
}
```

// response 
`status: 200`
```
{
 goma: {
    name: string;
    side: string;
  }, 
 to: {
   x: int, y: int, z: int 
 }
}
```

# New Dependencies
none

2023-07-25 14:21 UTC, allyusd requested changes
一些需要修正的地方

2023-07-25 14:28 UTC, Parkerhiphop commented on server/src/domain/constant/ERROR_MESSAGE.ts
> +}
key 要統一一下嗎？
有些有包 `''` 有些沒有

2023-07-25 16:34 UTC, allenh reviewed
* 糾正一下一些function命名的語意
  * has xyz at below <=> has xyz below (at是贅詞)
* 有些function沒有return type, 以ts來說每個function都有return type會比較好 因為ts會幫你做type inference
* 討論點：目前的unit test的寫法是按照feature在切割，這樣以後要改會比較困難因為要找出全部有關聯的feature，但假如是按照class或file來切割的話變成是只要有改到某個file那這個file的unit test就要改動 這樣的話可以用 `describe`形容feature然後在unit test的檔案裡切

2023-07-25 16:34 UTC, allenh commented on server/src/domain/constant/ERROR_MESSAGE.ts
> +}
+1

2023-07-25 16:34 UTC, allenh commented on server/src/domain/events/Event.ts
>  import Player from '../Player';
我覺得這個檔案應該要把每個interface分開 像：
```
- /events
-- index.ts (imports then exports all event interfaces, except the original event interface) 
-- Event.ts (has the main Event interface)
-- FurigomaEvent (the furigoma event interface)
-- ArataEvent (the arata event interface)
```

2023-07-25 16:34 UTC, allenh commented on server/src/domain/goma/tsconfig.json
> +{
why is this tsconfig needed specifically for goma?

2023-07-25 16:34 UTC, allenh commented on server/src/frameworks/data-services/data-model/GungiDataModel.ts
> +  private createCoordinate(coordinate: CoordinateData) {
add function return type

2023-07-25 16:34 UTC, allenh commented on server/src/frameworks/view-model/GungiViewModel.ts
這個被刪掉後是被哪裡取代了？

2023-07-25 16:34 UTC, allenh commented on server/src/usecases/Usecase.ts
> +  execute<View>(request: Request, presenter: Presenter<View>): Promise<View>;
感覺把 "execute" 改成 "present" 比較好聽

之後讀起來就會像：
Usecase U presents View V with presenter P
vs：
Usecase U executes View V with presenter P

2023-07-26 16:06 UTC, zhihdd commented on server/src/usecases/Usecase.ts
> +  execute<View>(request: Request, presenter: Presenter<View>): Promise<View>;
nice idea

2023-07-26 16:08 UTC, zhihdd commented on server/src/domain/Gungi.ts
> +    this._goteGomaOki = player.gomaOki;
for test

2023-07-26 17:05 UTC, zhihdd commented on server/src/domain/goma/tsconfig.json
> +{
I don't know lol. why is the file generated ?!!!!!!!

2023-07-26 17:05 UTC, zhihdd commented on server/src/frameworks/data-services/data-model/GungiDataModel.ts
> +  private createCoordinate(coordinate: CoordinateData) {
I'm curious about why I should add it. because type inferring can tell me what type it is.
could tell me your thought?

2023-07-26 17:05 UTC, zhihdd commented on server/src/frameworks/view-model/GungiViewModel.ts
replace by interface in presenter

2023-07-26 20:36 UTC, allenh commented on server/src/domain/GungiHan.ts
> +  private isOutOfBoundary(coordinate: Coordinate) {
Is there a specific use case where the client needs to know if it's "x and y" and "z" out of bound separately? If there is a separation then why doesn't the client need a separation between "x" and "y"? If not then shouldn't the client only need to know if the coordinate is out of bound regardless of which axis?

2023-07-26 20:37 UTC, allenh commented on server/src/domain/GungiHan.ts
> +  // create 9x9x3  not same memory array
Yes. I just want to point this out for future reference.

2023-07-26 21:58 UTC, allenh commented on server/src/frameworks/data-services/data-model/GungiDataModel.ts
> +  private createCoordinate(coordinate: CoordinateData) {
* by explicitly specifying the return type then typescript will do return type check so it reinforces overall typing
* Another reason is for increased readability

2023-07-26 22:02 UTC, allenh commented on server/src/domain/goma/tsconfig.json
> +{
Just delete it if it's not intended to be there

2023-10-03 14:35 UTC, zhihdd commented on server/src/domain/GungiHan.ts
> +        const sameSideGomas = col.filter((goma) => goma?.side === side);
延遲實作，先推進度，因為屬於規則模糊地帶，不影響整個遊戲

2023-10-03 15:09 UTC, allyusd approved these changes

2023-10-03 15:10 UTC, Parkerhiphop approved these changes
LGTM!
Let Get This Merged!

2023-10-03 15:10 UTC, noracami approved these changes
LGTM

2023-10-03 15:11 UTC, merged