#15 Feature/15 create gungi game
Game-as-a-Service/HUNTER-Gungi pull request #25
Opened 2023-10-04 16:00 UTC by zhihdd

#15 
# Description
send request to initialilze gungi game

# How to test
```
// api route
{POST} /gungi/create

// request
{ 
   players: { id: string; nickname: string }[] 
}

// response 
status: 200
{
  url: string 
}
```

# New Dependencies

2023-10-16 23:22 UTC, allenh requested changes
### General Comments
* add an e2e test for validating user input (ie. body should contain a list of players and it should be 2, otherwise return 400)
* think of other places where you need to be more defensive of inputs and where things will break

2023-10-16 23:22 UTC, allenh commented on server/src/usecases/Repository.ts
> +export default interface IRepository<T, InitRequest> {
I think this is confusing to read as a design pattern. You would only ever need to use this `InitRequest` _once_ and it's during `init`. I also don't think having the `create` method take anything else other than `T` is correct for a repository pattern design. However, I do understand why this is implemented this way. As a compromise, given our use case, I think it would make sense to use the `Partial` utility such as `create(item: T | Partial<T>)` and in the `CreateUsecase` massage the request data into something resembling the `Partial<Gungi>`type.

2023-10-16 23:22 UTC, allenh commented on server/src/frameworks/data-services/GungiRepository.ts
> +export class GungiRepository implements IRepository<Gungi, InitRequest> {
See my comments about `InitRequest` in `Repository.ts`

2023-11-14 14:12 UTC, noracami approved these changes
LGTM

2023-11-14 14:13 UTC, merged