GitHub action
Game-as-a-Service/HUNTER-Gungi pull request #8
Opened 2023-02-20 15:47 UTC by allyusd

# Description
加上 CI/CD，包含 Dockerfile, docker-compose 及 Github Actions

等目前的 Lint, Test, Docker Build and Push 流程確認後可以再加上 Deploy

# How to test

# New Dependencies

close #6

2023-02-21 14:52 UTC, noracami commented
main.yml 上需要加 `on: pull_request` 嗎

2023-02-28 19:35 UTC, allenh requested changes
可以把原本的 `docker-compose.yml` 刪掉這樣就會變成改名字(`docker-compose.yml` -> `docker-compose.local.yml`) 看起來比較清楚跟以後要加新的`docker-compose` 也比較方便

2023-02-28 19:36 UTC, allenh commented
另外好奇問一下 這個有測試過可以跑嗎?

2023-03-01 04:32 UTC, allenh approved these changes

2023-03-07 14:47 UTC, allenh requested changes

2023-03-07 14:47 UTC, allenh commented on frontend/docker/Dockerfile
> +CMD ["node_modules/.bin/next", "start"]
這邊可以像這樣寫

`package.json`
```
{
  "scripts": {
    "start": "next start"
  }
}
```

`Dockerfile`
```
# ...
CMD ["npm", "start"]
```

2023-03-07 14:47 UTC, allenh commented on server/docker/Dockerfile
> +CMD ["node", "dist/main"]
同上

2023-03-07 15:43 UTC, allenh approved these changes

2023-03-07 15:44 UTC, allenh commented
From Docker: https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#cmd

> When creating an image, you can bypass the package.json's start command and bake it directly into the image itself. First off this reduces the number of processes running inside of your container. Secondly it causes exit signals such as SIGTERM and SIGINT to be received by the Node.js process instead of npm swallowing them.

> CMD ["node","index.js"]

Approving PR.

2023-03-07 15:46 UTC, zhihdd approved these changes

2023-03-07 15:47 UTC, merged